# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'removevectorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoveVector(object):
    def setupUi(self, RemoveVector):
        RemoveVector.setObjectName("RemoveVector")
        RemoveVector.resize(358, 238)
        RemoveVector.setMinimumSize(QtCore.QSize(358, 238))
        self.verticalLayout = QtWidgets.QVBoxLayout(RemoveVector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(RemoveVector)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listVectors = QtWidgets.QListWidget(RemoveVector)
        self.listVectors.setObjectName("listVectors")
        self.verticalLayout.addWidget(self.listVectors)

        self.retranslateUi(RemoveVector)
        QtCore.QMetaObject.connectSlotsByName(RemoveVector)

    def retranslateUi(self, RemoveVector):
        _translate = QtCore.QCoreApplication.translate
        RemoveVector.setWindowTitle(_translate("RemoveVector", "Remove Vector"))
        self.label.setText(_translate("RemoveVector", "Double click on the vector that you want to remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemoveVector = QtWidgets.QDialog()
    ui = Ui_RemoveVector()
    ui.setupUi(RemoveVector)
    RemoveVector.show()
    sys.exit(app.exec_())
