# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'removepointDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemovePoint(object):
    def setupUi(self, RemovePoint):
        RemovePoint.setObjectName("RemovePoint")
        RemovePoint.resize(358, 238)
        RemovePoint.setMinimumSize(QtCore.QSize(358, 238))
        self.verticalLayout = QtWidgets.QVBoxLayout(RemovePoint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(RemovePoint)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listPoints = QtWidgets.QListWidget(RemovePoint)
        self.listPoints.setObjectName("listPoints")
        self.verticalLayout.addWidget(self.listPoints)

        self.retranslateUi(RemovePoint)
        QtCore.QMetaObject.connectSlotsByName(RemovePoint)

    def retranslateUi(self, RemovePoint):
        _translate = QtCore.QCoreApplication.translate
        RemovePoint.setWindowTitle(_translate("RemovePoint", "Remove Point"))
        self.label.setText(_translate("RemovePoint", "Double click on the point that you want to remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemovePoint = QtWidgets.QDialog()
    ui = Ui_RemovePoint()
    ui.setupUi(RemovePoint)
    RemovePoint.show()
    sys.exit(app.exec_())
