# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xnameDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_XName(object):
    def setupUi(self, XName):
        XName.setObjectName("XName")
        XName.resize(286, 120)
        XName.setMinimumSize(QtCore.QSize(286, 0))
        self.gridLayout = QtWidgets.QGridLayout(XName)
        self.gridLayout.setObjectName("gridLayout")
        self.NameLine = QtWidgets.QLineEdit(XName)
        self.NameLine.setObjectName("NameLine")
        self.gridLayout.addWidget(self.NameLine, 2, 1, 1, 1)
        self.TextSizeLine = QtWidgets.QSpinBox(XName)
        self.TextSizeLine.setMinimum(1)
        self.TextSizeLine.setProperty("value", 16)
        self.TextSizeLine.setObjectName("TextSizeLine")
        self.gridLayout.addWidget(self.TextSizeLine, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(XName)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(XName)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.OkButton = QtWidgets.QPushButton(XName)
        self.OkButton.setObjectName("OkButton")
        self.gridLayout.addWidget(self.OkButton, 3, 0, 1, 2)

        self.retranslateUi(XName)
        QtCore.QMetaObject.connectSlotsByName(XName)

    def retranslateUi(self, XName):
        _translate = QtCore.QCoreApplication.translate
        XName.setWindowTitle(_translate("XName", "X Axis Name"))
        self.NameLine.setText(_translate("XName", "Name"))
        self.label.setText(_translate("XName", "Text size"))
        self.label_2.setText(_translate("XName", "Name"))
        self.OkButton.setText(_translate("XName", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    XName = QtWidgets.QDialog()
    ui = Ui_XName()
    ui.setupUi(XName)
    XName.show()
    sys.exit(app.exec_())
