# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ynameDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YName(object):
    def setupUi(self, YName):
        YName.setObjectName("YName")
        YName.resize(286, 120)
        YName.setMinimumSize(QtCore.QSize(286, 0))
        self.gridLayout = QtWidgets.QGridLayout(YName)
        self.gridLayout.setObjectName("gridLayout")
        self.NameLine = QtWidgets.QLineEdit(YName)
        self.NameLine.setObjectName("NameLine")
        self.gridLayout.addWidget(self.NameLine, 2, 1, 1, 1)
        self.TextSizeLine = QtWidgets.QSpinBox(YName)
        self.TextSizeLine.setMinimum(1)
        self.TextSizeLine.setProperty("value", 16)
        self.TextSizeLine.setObjectName("TextSizeLine")
        self.gridLayout.addWidget(self.TextSizeLine, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(YName)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(YName)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.OkButton = QtWidgets.QPushButton(YName)
        self.OkButton.setObjectName("OkButton")
        self.gridLayout.addWidget(self.OkButton, 3, 0, 1, 2)

        self.retranslateUi(YName)
        QtCore.QMetaObject.connectSlotsByName(YName)

    def retranslateUi(self, YName):
        _translate = QtCore.QCoreApplication.translate
        YName.setWindowTitle(_translate("YName", "Y Axis Name"))
        self.NameLine.setText(_translate("YName", "Name"))
        self.label.setText(_translate("YName", "Text size"))
        self.label_2.setText(_translate("YName", "Name"))
        self.OkButton.setText(_translate("YName", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    YName = QtWidgets.QDialog()
    ui = Ui_YName()
    ui.setupUi(YName)
    YName.show()
    sys.exit(app.exec_())
